/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions

import java.nio.{ByteBuffer, ByteOrder}
import java.time.{Duration, ZoneOffset}

import org.apache.spark.SparkFunSuite
import org.apache.spark.sql.catalyst.expressions.variant.VariantExpressionEvalUtils
import org.apache.spark.sql.catalyst.util.{ArrayBasedMapData, DateTimeUtils, GenericArrayData, IntervalUtils}
import org.apache.spark.sql.types._
import org.apache.spark.unsafe.types.{CalendarInterval, TimestampNanosVal, UTF8String, VariantVal}

// ---------------------------------------------------------------------------
// Golden printer: regenerate pinned values and paste the printed map below.
//
// Run with:
//   build/sbt 'catalyst/Test/runMain \
//     org.apache.spark.sql.catalyst.expressions.XXH3TypeCoverageGoldenPrinter'
// ---------------------------------------------------------------------------
object XXH3TypeCoverageGoldenPrinter {

  /**
   * Pinned golden values for [[XXH3TypeCoverageTest]].
   *
   * Generated by running `main` on 2026-06-01. Regenerate with:
   *   build/sbt 'catalyst/Test/runMain \
   *     org.apache.spark.sql.catalyst.expressions.XXH3TypeCoverageGoldenPrinter'
   * then paste the printed map here and re-run [[XXH3TypeCoverageTest]].
   */
  // scalastyle:off line.size.limit
  val goldenXxHash3: Map[String, Long] = Map(
    "null/null"    -> 0L,
    "bool/false"   -> 5238470482016868669L,
    "bool/true"    -> -2665511616818817272L,
    "bool/null"    -> 0L,
    "byte/0"       -> 5238470482016868669L,
    "byte/1"       -> -2665511616818817272L,
    "byte/-1"      -> -3644788059813222868L,
    "byte/max"     -> 7935356304610272077L,
    "byte/min"     -> 2071493720539283278L,
    "byte/null"    -> 0L,
    "short/0"      -> 5238470482016868669L,
    "short/1"      -> -2665511616818817272L,
    "short/-1"     -> -3644788059813222868L,
    "short/max"    -> 2548825873647319235L,
    "short/min"    -> 960799505904963048L,
    "short/null"   -> 0L,
    "int/0"        -> 5238470482016868669L,
    "int/1"        -> -2665511616818817272L,
    "int/-1"       -> -3644788059813222868L,
    "int/max"      -> 6147526096378114303L,
    "int/min"      -> 7513848233174832419L,
    "int/null"     -> 0L,
    "long/0"       -> -4072596861322023719L,
    "long/1"       -> 3439722301264460078L,
    "long/-1"      -> 5841669975847748627L,
    "long/max"     -> -6758830778922508474L,
    "long/min"     -> -9038965835861193121L,
    "long/null"    -> 0L,
    "float/0"      -> 5238470482016868669L,
    "float/-0"     -> 5238470482016868669L,
    "float/1.5"    -> -5914513013247554128L,
    "float/NaN"    -> 4713201242463034323L,
    "float/+Inf"   -> 7407755016406576001L,
    "float/-Inf"   -> 6855633992648319089L,
    "float/null"   -> 0L,
    "double/0"     -> -4072596861322023719L,
    "double/-0"    -> -4072596861322023719L,
    "double/1.5"   -> 2693614958850487384L,
    "double/NaN"   -> 767333564151873895L,
    "double/+Inf"  -> 3862676201523092338L,
    "double/-Inf"  -> -7607982011244918730L,
    "double/null"  -> 0L,
    "dec10/0"      -> -4072596861322023719L,
    "dec10/1"      -> 3439722301264460078L,
    "dec10/-1"     -> 5841669975847748627L,
    "dec10/null"   -> 0L,
    "dec38/0"      -> -4302098779834749733L,
    "dec38/big"    -> -5623482264082953715L,
    "dec38/null"   -> 0L,
    "str/empty"    -> 3244421341483603138L,
    "str/hello"    -> -3150353794653054837L,
    "str/17"       -> -8532247153275348463L,
    "str/129"      -> -1357050840007899287L,
    "str/300"      -> 5566209743561438005L,
    "str/null"     -> 0L,
    "bin/empty"    -> 3244421341483603138L,
    "bin/1byte"    -> -4302098779834749733L,
    "bin/8bytes"   -> 1653410307359580823L,
    "bin/300"      -> 2821465035767473961L,
    "bin/null"     -> 0L,
    "date/epoch"   -> 5238470482016868669L,
    "date/2024"    -> -7475544369297746522L,
    "date/1800"    -> -7273294491923069338L,
    "date/null"    -> 0L,
    "ts/epoch"     -> -4072596861322023719L,
    "ts/2024"      -> -3965608774495983795L,
    "ts/null"      -> 0L,
    "tsntz/epoch"  -> -4072596861322023719L,
    "tsntz/2024"   -> -3965608774495983795L,
    "tsntz/null"   -> 0L,
    "dt/0"         -> -4072596861322023719L,
    "dt/1day"      -> 3303014626796789818L,
    "dt/-1day"     -> 4303847845211075027L,
    "dt/null"      -> 0L,
    "ym/0"         -> 5238470482016868669L,
    "ym/12"        -> 5420799020890387807L,
    "ym/-6"        -> -2674203829338676892L,
    "ym/null"      -> 0L,
    "cal/zero"     -> 3033773462233533796L,
    "cal/mixed"    -> 6397982233747637664L,
    "cal/null"     -> 0L,
    "tsntz9/epoch" -> -8531844162781733237L,
    "tsntz9/mixed" -> 6030512949845109462L,
    "tsntz9/null"  -> 0L,
    "tsltz9/epoch" -> -8531844162781733237L,
    "tsltz9/mixed" -> 6030512949845109462L,
    "tsltz9/null"  -> 0L,
    "aint/empty"   -> 5238470482016868669L,
    "aint/123"     -> 9114663965641668645L,
    "aint/bounds"  -> -2562941173265889007L,
    "aint/null"    -> 0L,
    "aintn/nn"     -> 8139571457004014537L,
    "aintn/1n3"    -> 7530171421075162815L,
    "astr/mix"     -> 4192268917085169418L,
    "map/empty"    -> -4072596861322023719L,
    "map/mix"      -> -7775835659524071725L,
    "map/null"     -> 0L,
    "st/vals"      -> 4256773294053208696L,
    "st/nulls"     -> -3976746810775836259L,
    "st/null"      -> 0L,
    "var/null_v"   -> -4072596861322023719L,
    "var/bool"     -> -2665511616818817272L,
    "var/long"     -> -3051478158665635896L,
    "var/double"   -> 2375286594789961030L,
    "var/string"   -> -7685981735718036227L,
    "var/object"   -> 4081605381438641973L,
    "var/array"    -> -8113289783193167918L,
    "var/sql_null" -> 0L
  )
  // scalastyle:on line.size.limit

  def main(args: Array[String]): Unit = printAll()

  // scalastyle:off println
  def printAll(): Unit = {
    println(
      s"""// XXH3 type-coverage golden values - generated ${java.time.LocalDate.now()}
         |// XxHash3 seed=0; XxHash128 shown as (high64, low64) big-endian pairs.
         |// Regenerate: build/sbt 'catalyst/Test/runMain \\
         |//   org.apache.spark.sql.catalyst.expressions.XXH3TypeCoverageGoldenPrinter'
         |""".stripMargin)

    section("NullType")
    emit("null/null",    mkLit(null, NullType))

    section("BooleanType")
    emit("bool/false",   mkLit(false, BooleanType))
    emit("bool/true",    mkLit(true, BooleanType))
    emit("bool/null",    nullLit(BooleanType))

    section("ByteType")
    emit("byte/0",       mkLit(0.toByte, ByteType))
    emit("byte/1",       mkLit(1.toByte, ByteType))
    emit("byte/-1",      mkLit((-1).toByte, ByteType))
    emit("byte/max",     mkLit(Byte.MaxValue, ByteType))
    emit("byte/min",     mkLit(Byte.MinValue, ByteType))
    emit("byte/null",    nullLit(ByteType))

    section("ShortType")
    emit("short/0",      mkLit(0.toShort, ShortType))
    emit("short/1",      mkLit(1.toShort, ShortType))
    emit("short/-1",     mkLit((-1).toShort, ShortType))
    emit("short/max",    mkLit(Short.MaxValue, ShortType))
    emit("short/min",    mkLit(Short.MinValue, ShortType))
    emit("short/null",   nullLit(ShortType))

    section("IntegerType")
    emit("int/0",        mkLit(0, IntegerType))
    emit("int/1",        mkLit(1, IntegerType))
    emit("int/-1",       mkLit(-1, IntegerType))
    emit("int/max",      mkLit(Int.MaxValue, IntegerType))
    emit("int/min",      mkLit(Int.MinValue, IntegerType))
    emit("int/null",     nullLit(IntegerType))

    section("LongType")
    emit("long/0",       mkLit(0L, LongType))
    emit("long/1",       mkLit(1L, LongType))
    emit("long/-1",      mkLit(-1L, LongType))
    emit("long/max",     mkLit(Long.MaxValue, LongType))
    emit("long/min",     mkLit(Long.MinValue, LongType))
    emit("long/null",    nullLit(LongType))

    section("FloatType")
    emit("float/0",      mkLit(0.0f, FloatType))
    emit("float/-0",     mkLit(-0.0f, FloatType))
    emit("float/1.5",    mkLit(1.5f, FloatType))
    emit("float/NaN",    mkLit(Float.NaN, FloatType))
    emit("float/+Inf",   mkLit(Float.PositiveInfinity, FloatType))
    emit("float/-Inf",   mkLit(Float.NegativeInfinity, FloatType))
    emit("float/null",   nullLit(FloatType))

    section("DoubleType")
    emit("double/0",     mkLit(0.0, DoubleType))
    emit("double/-0",    mkLit(-0.0, DoubleType))
    emit("double/1.5",   mkLit(1.5, DoubleType))
    emit("double/NaN",   mkLit(Double.NaN, DoubleType))
    emit("double/+Inf",  mkLit(Double.PositiveInfinity, DoubleType))
    emit("double/-Inf",  mkLit(Double.NegativeInfinity, DoubleType))
    emit("double/null",  nullLit(DoubleType))

    section("DecimalType(10,0)")
    emit("dec10/0",      mkLit(Decimal(0), DecimalType.USER_DEFAULT))
    emit("dec10/1",      mkLit(Decimal(1), DecimalType.USER_DEFAULT))
    emit("dec10/-1",     mkLit(Decimal(-1), DecimalType.USER_DEFAULT))
    emit("dec10/null",   nullLit(DecimalType.USER_DEFAULT))

    section("DecimalType(38,18)")
    emit("dec38/0",      mkLit(Decimal(0), DecimalType.SYSTEM_DEFAULT))
    emit("dec38/big",    mkLit(Decimal("123456.789012345678"), DecimalType.SYSTEM_DEFAULT))
    emit("dec38/null",   nullLit(DecimalType.SYSTEM_DEFAULT))

    section("StringType")
    emit("str/empty",    mkLit(UTF8String.fromString(""), StringType))
    emit("str/hello",    mkLit(UTF8String.fromString("hello world"), StringType))
    emit("str/17",       mkLit(UTF8String.fromString("x" * 17), StringType))
    emit("str/129",      mkLit(UTF8String.fromString("y" * 129), StringType))
    emit("str/300",      mkLit(UTF8String.fromString("z" * 300), StringType))
    emit("str/null",     nullLit(StringType))

    section("BinaryType")
    emit("bin/empty",    mkLit(Array.empty[Byte], BinaryType))
    emit("bin/1byte",    mkLit(Array[Byte](0), BinaryType))
    emit("bin/8bytes",   mkLit(Array[Byte](1, 2, 3, 4, 5, 6, 7, 8), BinaryType))
    emit("bin/300",      mkLit(Array.fill[Byte](300)(42.toByte), BinaryType))
    emit("bin/null",     nullLit(BinaryType))

    val date1 = DateTimeUtils.stringToDate(UTF8String.fromString("2024-01-15")).get
    val dateNeg = DateTimeUtils.stringToDate(UTF8String.fromString("1800-06-01")).get
    section("DateType")
    emit("date/epoch",   mkLit(0, DateType))
    emit("date/2024",    mkLit(date1, DateType))
    emit("date/1800",    mkLit(dateNeg, DateType))
    emit("date/null",    nullLit(DateType))

    val ts1 = DateTimeUtils.stringToTimestamp(
      UTF8String.fromString("2024-01-15 12:34:56.789012"), ZoneOffset.UTC).get
    section("TimestampType")
    emit("ts/epoch",     mkLit(0L, TimestampType))
    emit("ts/2024",      mkLit(ts1, TimestampType))
    emit("ts/null",      nullLit(TimestampType))

    val tsNtz1 = DateTimeUtils.stringToTimestampWithoutTimeZone(
      UTF8String.fromString("2024-01-15 12:34:56.789012")).get
    section("TimestampNTZType")
    emit("tsntz/epoch",  mkLit(0L, TimestampNTZType))
    emit("tsntz/2024",   mkLit(tsNtz1, TimestampNTZType))
    emit("tsntz/null",   nullLit(TimestampNTZType))

    val oneDayMicros = Duration.ofDays(1).toNanos / 1000L
    section("DayTimeIntervalType")
    emit("dt/0",         mkLit(0L, DayTimeIntervalType()))
    emit("dt/1day",      mkLit(oneDayMicros, DayTimeIntervalType()))
    emit("dt/-1day",     mkLit(-oneDayMicros, DayTimeIntervalType()))
    emit("dt/null",      nullLit(DayTimeIntervalType()))

    section("YearMonthIntervalType")
    emit("ym/0",         mkLit(0, YearMonthIntervalType()))
    emit("ym/12",        mkLit(12, YearMonthIntervalType()))
    emit("ym/-6",        mkLit(-6, YearMonthIntervalType()))
    emit("ym/null",      nullLit(YearMonthIntervalType()))

    val iv0 = new CalendarInterval(0, 0, 0L)
    val iv1 = IntervalUtils.stringToInterval(
      UTF8String.fromString("interval 1 year 2 months 3 days 4 hours"))
    section("CalendarIntervalType")
    emit("cal/zero",     mkLit(iv0, CalendarIntervalType))
    emit("cal/mixed",    mkLit(iv1, CalendarIntervalType))
    emit("cal/null",     nullLit(CalendarIntervalType))

    val tsNanosEpoch = TimestampNanosVal.fromParts(0L, 0.toShort)
    val tsNanosMixed = TimestampNanosVal.fromParts(1705318496789012L, 500.toShort)
    section("TimestampNTZNanosType(9)")
    emit("tsntz9/epoch", mkLit(tsNanosEpoch, TimestampNTZNanosType(9)))
    emit("tsntz9/mixed", mkLit(tsNanosMixed, TimestampNTZNanosType(9)))
    emit("tsntz9/null",  nullLit(TimestampNTZNanosType(9)))
    section("TimestampLTZNanosType(9)")
    emit("tsltz9/epoch", mkLit(tsNanosEpoch, TimestampLTZNanosType(9)))
    emit("tsltz9/mixed", mkLit(tsNanosMixed, TimestampLTZNanosType(9)))
    emit("tsltz9/null",  nullLit(TimestampLTZNanosType(9)))

    section("ArrayType(IntegerType, containsNull=false)")
    val aintDt = ArrayType(IntegerType, containsNull = false)
    emit("aint/empty",   mkLit(new GenericArrayData(Array[Any]()), aintDt))
    emit("aint/123",     mkLit(new GenericArrayData(Array[Any](1, 2, 3)), aintDt))
    emit("aint/bounds",  mkLit(new GenericArrayData(Array[Any](Int.MinValue, 0, Int.MaxValue)), aintDt))
    emit("aint/null",    nullLit(aintDt))

    section("ArrayType(IntegerType, containsNull=true) with actual nulls")
    val aintNDt = ArrayType(IntegerType, containsNull = true)
    emit("aintn/nn",     mkLit(new GenericArrayData(Array[Any](null, null)), aintNDt))
    emit("aintn/1n3",    mkLit(new GenericArrayData(Array[Any](1, null, 3)), aintNDt))

    section("ArrayType(StringType, containsNull=true)")
    val astrDt = ArrayType(StringType, containsNull = true)
    val astrData = new GenericArrayData(Array[Any](
      UTF8String.fromString("hello"), null, UTF8String.fromString("world")))
    emit("astr/mix",     mkLit(astrData, astrDt))

    section("MapType(IntegerType, StringType, valueContainsNull=true)")
    val mapDt = MapType(IntegerType, StringType, valueContainsNull = true)
    emit("map/empty",    mkLit(
      new ArrayBasedMapData(new GenericArrayData(Array[Any]()), new GenericArrayData(Array[Any]())),
      mapDt))
    emit("map/mix",      mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](1, 2, 3)),
        new GenericArrayData(Array[Any](UTF8String.fromString("a"), null,
                                        UTF8String.fromString("c")))),
      mapDt))
    emit("map/null",     nullLit(mapDt))

    section("StructType(int, string, long)")
    val stDt = new StructType().add("a", IntegerType).add("b", StringType).add("c", LongType)
    emit("st/vals",      mkLit(
      new GenericInternalRow(Array[Any](42, UTF8String.fromString("hello"), 99L)), stDt))
    emit("st/nulls",     mkLit(new GenericInternalRow(Array[Any](null, null, null)), stDt))
    emit("st/null",      nullLit(stDt))

    section("VariantType - logical-type dispatch")
    emit("var/null_v",   mkLit(parseVariant("null"), VariantType))
    emit("var/bool",     mkLit(parseVariant("true"), VariantType))
    emit("var/long",     mkLit(parseVariant("42"), VariantType))
    emit("var/double",   mkLit(parseVariant("3.14"), VariantType))
    emit("var/string",   mkLit(parseVariant("\"hello\""), VariantType))
    emit("var/object",   mkLit(parseVariant("{\"a\":1,\"b\":2}"), VariantType))
    emit("var/array",    mkLit(parseVariant("[1,2,3]"), VariantType))
    emit("var/sql_null", nullLit(VariantType))
  }
  // scalastyle:on println

  private val COL = 44  // label column width

  // scalastyle:off println
  private def section(name: String): Unit = println(s"\n  // $name")

  private def emit(label: String, lit: Literal): Unit = {
    val h3: Any = XxHash3(Seq(lit), 0L).eval(null)
    val h128: Any = new XxHash128(Seq(lit)).eval(null)

    val h3str = h3 match {
      case l: Long => s"${l}L"
      case null    => "null /* XxHash3 should never return null */"
    }

    val h128str = h128 match {
      case null => "null"
      case bytes: Array[Byte] =>
        val buf = ByteBuffer.wrap(bytes).order(ByteOrder.BIG_ENDIAN)
        val hi = buf.getLong()
        val lo = buf.getLong()
        s"high=${hi}L low=${lo}L"
    }

    val key = s""""$label""""
    println(s"  ${key.padTo(COL, ' ')} -> ${h3str.padTo(26, ' ')}  // 128: $h128str")
  }
  // scalastyle:on println

  private def mkLit[T](value: T, dt: DataType): Literal = Literal.create(value, dt)
  private def nullLit(dt: DataType): Literal = Literal.create(null, dt)
  private def parseVariant(json: String): VariantVal =
    VariantExpressionEvalUtils.parseJson(UTF8String.fromString(json))
}

/**
 * Type-coverage regression tests for [[XxHash3]] (64-bit) and [[XxHash128]] (128-bit).
 *
 * Every Spark SQL type is exercised with representative values including nulls, arrays with
 * null/non-null elements, maps, and nested structs. The suite gives two guarantees per type:
 *
 *   1. **Codegen consistency** -- interpreted result == codegen result (ensured by
 *      [[ExpressionEvalHelper.checkEvaluation]] which runs both paths and compares).
 *   2. **Determinism** -- XxHash128 returns identical bytes when evaluated twice (catches
 *      misuse of mutable state in the codegen-generated path).
 *
 * Pinned golden values live in [[XXH3TypeCoverageGoldenPrinter.goldenXxHash3]] above.
 * To regenerate after an intentional algorithm change, run the printer's `main` method
 * and paste the output back into that map.
 */
class XXH3TypeCoverageTest extends SparkFunSuite with ExpressionEvalHelper {

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  private def check3(lit: Expression): Unit = {
    val expr = XxHash3(Seq(lit), 0L)
    checkEvaluation(expr, expr.eval(null))
  }

  private def check3seeded(lit: Expression, seed: Long): Unit = {
    val expr = XxHash3(Seq(lit), seed)
    checkEvaluation(expr, expr.eval(null))
  }

  private def check128(lit: Expression): Unit = {
    val expr = new XxHash128(Seq(lit))
    checkEvaluation(expr, expr.eval(null))
  }

  private def checkBoth(lit: Expression): Unit = { check3(lit); check128(lit) }

  private def mkLit[T](value: T, dt: DataType): Literal = Literal.create(value, dt)
  private def nullLit(dt: DataType): Literal = Literal.create(null, dt)

  // ---------------------------------------------------------------------------
  // Scalar types
  // ---------------------------------------------------------------------------

  test("NullType") {
    checkBoth(nullLit(NullType))
  }

  test("BooleanType") {
    checkBoth(mkLit(false, BooleanType))
    checkBoth(mkLit(true, BooleanType))
    checkBoth(nullLit(BooleanType))
  }

  test("ByteType") {
    Seq(0.toByte, 1.toByte, -1.toByte, Byte.MaxValue, Byte.MinValue).foreach { v =>
      checkBoth(mkLit(v, ByteType))
    }
    checkBoth(nullLit(ByteType))
  }

  test("ShortType") {
    Seq(0.toShort, 1.toShort, -1.toShort, Short.MaxValue, Short.MinValue).foreach { v =>
      checkBoth(mkLit(v, ShortType))
    }
    checkBoth(nullLit(ShortType))
  }

  test("IntegerType") {
    Seq(0, 1, -1, Int.MaxValue, Int.MinValue, 42).foreach { v =>
      checkBoth(mkLit(v, IntegerType))
    }
    checkBoth(nullLit(IntegerType))
  }

  test("LongType") {
    Seq(0L, 1L, -1L, Long.MaxValue, Long.MinValue, 1234567890123L).foreach { v =>
      checkBoth(mkLit(v, LongType))
    }
    checkBoth(nullLit(LongType))
  }

  test("FloatType") {
    Seq(0.0f, -0.0f, 1.5f, -1.5f, Float.NaN,
        Float.PositiveInfinity, Float.NegativeInfinity,
        Float.MaxValue, Float.MinPositiveValue).foreach { v =>
      checkBoth(mkLit(v, FloatType))
    }
    checkBoth(nullLit(FloatType))
  }

  test("DoubleType") {
    Seq(0.0, -0.0, 1.5, -1.5, Double.NaN,
        Double.PositiveInfinity, Double.NegativeInfinity,
        Double.MaxValue, Double.MinPositiveValue).foreach { v =>
      checkBoth(mkLit(v, DoubleType))
    }
    checkBoth(nullLit(DoubleType))
  }

  test("DecimalType - USER_DEFAULT (10,0)") {
    val dt = DecimalType.USER_DEFAULT
    Seq(Decimal(0), Decimal(1), Decimal(-1), Decimal(Int.MaxValue.toLong)).foreach { v =>
      checkBoth(mkLit(v, dt))
    }
    checkBoth(nullLit(dt))
  }

  test("DecimalType - SYSTEM_DEFAULT (38,18)") {
    val dt = DecimalType.SYSTEM_DEFAULT
    Seq(Decimal(0), Decimal("123456.789012345678"), Decimal("-9999999999999999999.999999999999999999"))
      .foreach { v => checkBoth(mkLit(v, dt)) }
    checkBoth(nullLit(dt))
  }

  test("DecimalType - various precisions and scales") {
    for ((prec, scale) <- Seq((10, 2), (18, 6), (38, 10))) {
      val dt = DecimalType(prec, scale)
      checkBoth(mkLit(Decimal(0), dt))
      checkBoth(mkLit(Decimal("12345.67"), dt))
      checkBoth(nullLit(dt))
    }
  }

  test("StringType") {
    val strs = Seq("", "hello world", "apache spark xxhash3",
                   "x" * 17,   // 17-128 byte path
                   "y" * 129,  // 129-240 byte path
                   "z" * 300)  // >240 byte long-input accumulator path
    strs.foreach { s =>
      checkBoth(mkLit(UTF8String.fromString(s), StringType))
    }
    checkBoth(nullLit(StringType))
  }

  test("BinaryType") {
    Seq(Array.empty[Byte],
        Array[Byte](0),
        Array[Byte](1, 2, 3, 4, 5, 6, 7, 8),
        Array.fill[Byte](17)(0xab.toByte),  // 17-byte boundary
        Array.fill[Byte](300)(42.toByte))   // >240 bytes
      .foreach { v => checkBoth(mkLit(v, BinaryType)) }
    checkBoth(nullLit(BinaryType))
  }

  test("DateType") {
    val epoch = 0  // 1970-01-01
    val date1 = DateTimeUtils.stringToDate(UTF8String.fromString("2024-01-15")).get
    val dateNeg = DateTimeUtils.stringToDate(UTF8String.fromString("1800-06-01")).get
    Seq(epoch, date1, dateNeg).foreach { v => checkBoth(mkLit(v, DateType)) }
    checkBoth(nullLit(DateType))
  }

  test("TimestampType") {
    val epoch = 0L
    val ts1 = DateTimeUtils.stringToTimestamp(
      UTF8String.fromString("2024-01-15 12:34:56.789012"), ZoneOffset.UTC).get
    val tsNeg = DateTimeUtils.stringToTimestamp(
      UTF8String.fromString("1800-06-01 00:00:00"), ZoneOffset.UTC).get
    Seq(epoch, ts1, tsNeg).foreach { v => checkBoth(mkLit(v, TimestampType)) }
    checkBoth(nullLit(TimestampType))
  }

  test("TimestampNTZType") {
    val epoch = 0L
    val ts1 = DateTimeUtils.stringToTimestampWithoutTimeZone(
      UTF8String.fromString("2024-01-15 12:34:56.789012")).get
    Seq(epoch, ts1).foreach { v => checkBoth(mkLit(v, TimestampNTZType)) }
    checkBoth(nullLit(TimestampNTZType))
  }

  test("DayTimeIntervalType") {
    val oneDayMicros = Duration.ofDays(1).toNanos / 1000L
    Seq(0L, oneDayMicros, -oneDayMicros, Long.MaxValue / 2).foreach { v =>
      checkBoth(mkLit(v, DayTimeIntervalType()))
    }
    checkBoth(nullLit(DayTimeIntervalType()))
  }

  test("YearMonthIntervalType") {
    Seq(0, 1, 12, -6, Int.MaxValue / 2).foreach { v =>
      checkBoth(mkLit(v, YearMonthIntervalType()))
    }
    checkBoth(nullLit(YearMonthIntervalType()))
  }

  test("CalendarIntervalType") {
    val iv0 = new CalendarInterval(0, 0, 0L)
    val iv1 = IntervalUtils.stringToInterval(
      UTF8String.fromString("interval 1 year 2 months 3 days 4 hours"))
    val ivNeg = IntervalUtils.stringToInterval(
      UTF8String.fromString("interval -5 years 10 months"))
    Seq(iv0, iv1, ivNeg).foreach { v => checkBoth(mkLit(v, CalendarIntervalType)) }
    checkBoth(nullLit(CalendarIntervalType))
  }

  test("TimestampNTZNanosType / TimestampLTZNanosType") {
    val epoch  = TimestampNanosVal.fromParts(0L, 0.toShort)
    val mixed  = TimestampNanosVal.fromParts(1705318496789012L, 500.toShort)
    val negMicros = TimestampNanosVal.fromParts(-1L, 999.toShort)
    Seq(TimestampNTZNanosType(9), TimestampLTZNanosType(9)).foreach { dt =>
      Seq(epoch, mixed, negMicros).foreach { v => checkBoth(mkLit(v, dt)) }
      checkBoth(nullLit(dt))
    }
  }

  // ---------------------------------------------------------------------------
  // ArrayType - element types and null combinations
  // ---------------------------------------------------------------------------

  test("ArrayType(IntegerType) - non-nullable elements") {
    val dt = ArrayType(IntegerType, containsNull = false)
    Seq(
      new GenericArrayData(Array[Any]()),
      new GenericArrayData(Array[Any](1, 2, 3)),
      new GenericArrayData(Array[Any](Int.MinValue, 0, Int.MaxValue))
    ).foreach { v => checkBoth(mkLit(v, dt)) }
    checkBoth(nullLit(dt))
  }

  test("ArrayType(IntegerType) - nullable elements, with actual nulls") {
    val dt = ArrayType(IntegerType, containsNull = true)
    Seq(
      new GenericArrayData(Array[Any](null, null)),
      new GenericArrayData(Array[Any](1, null, 3)),
      new GenericArrayData(Array[Any](null, 2, null))
    ).foreach { v => checkBoth(mkLit(v, dt)) }
  }

  test("ArrayType(LongType) - nullable elements") {
    val dt = ArrayType(LongType, containsNull = true)
    checkBoth(mkLit(
      new GenericArrayData(Array[Any](0L, Long.MaxValue, null, Long.MinValue)), dt))
  }

  test("ArrayType(StringType) - nullable elements") {
    val dt = ArrayType(StringType, containsNull = true)
    val data = Array[Any](
      UTF8String.fromString("hello"),
      null,
      UTF8String.fromString("world"),
      UTF8String.fromString("x" * 300))
    checkBoth(mkLit(new GenericArrayData(data), dt))
  }

  test("ArrayType(DoubleType) - NaN and -0.0") {
    val dt = ArrayType(DoubleType, containsNull = true)
    val data = Array[Any](0.0, -0.0, Double.NaN, null, 1.5, Double.PositiveInfinity)
    checkBoth(mkLit(new GenericArrayData(data), dt))
  }

  test("ArrayType(BinaryType) - nullable elements") {
    val dt = ArrayType(BinaryType, containsNull = true)
    val data = Array[Any](Array[Byte](1, 2), null, Array.empty[Byte],
                          Array.fill[Byte](300)(7.toByte))
    checkBoth(mkLit(new GenericArrayData(data), dt))
  }

  test("ArrayType(BooleanType) - nullable elements") {
    val dt = ArrayType(BooleanType, containsNull = true)
    val data = Array[Any](true, false, null, true)
    checkBoth(mkLit(new GenericArrayData(data), dt))
  }

  test("ArrayType(FloatType) - nullable elements") {
    val dt = ArrayType(FloatType, containsNull = true)
    val data = Array[Any](1.5f, null, Float.NaN, -0.0f)
    checkBoth(mkLit(new GenericArrayData(data), dt))
  }

  test("ArrayType(DecimalType) - nullable elements") {
    val dt = ArrayType(DecimalType.SYSTEM_DEFAULT, containsNull = true)
    val data = Array[Any](Decimal(0), Decimal("123.456"), null, Decimal("-999.1"))
    checkBoth(mkLit(new GenericArrayData(data), dt))
  }

  test("ArrayType nested - Array of Array of Int") {
    val innerDt = ArrayType(IntegerType, containsNull = false)
    val outerDt = ArrayType(innerDt, containsNull = true)
    val inner1 = new GenericArrayData(Array[Any](1, 2, 3))
    val inner2 = new GenericArrayData(Array[Any](4, 5, 6))
    val inner3 = new GenericArrayData(Array[Any]())
    checkBoth(mkLit(new GenericArrayData(Array[Any](inner1, null, inner2, inner3)), outerDt))
    checkBoth(mkLit(new GenericArrayData(Array[Any]()), outerDt))
  }

  // ---------------------------------------------------------------------------
  // MapType - key/value type and null combinations
  // ---------------------------------------------------------------------------

  test("MapType(IntegerType, StringType) - nullable values") {
    val dt = MapType(IntegerType, StringType, valueContainsNull = true)
    // empty
    checkBoth(mkLit(
      new ArrayBasedMapData(new GenericArrayData(Array[Any]()), new GenericArrayData(Array[Any]())),
      dt))
    // some null values
    checkBoth(mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](1, 2, 3)),
        new GenericArrayData(Array[Any](UTF8String.fromString("a"), null, UTF8String.fromString("c")))),
      dt))
    // all null values
    checkBoth(mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](10, 20)),
        new GenericArrayData(Array[Any](null, null))),
      dt))
    checkBoth(nullLit(dt))
  }

  test("MapType(StringType, StringType) - no nulls and all-null values") {
    val dt = MapType(StringType, StringType, valueContainsNull = true)
    // no nulls
    checkBoth(mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](UTF8String.fromString("x"), UTF8String.fromString("y"))),
        new GenericArrayData(Array[Any](UTF8String.fromString("1"), UTF8String.fromString("2")))),
      dt))
    // all-null values
    checkBoth(mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](UTF8String.fromString("k1"), UTF8String.fromString("k2"))),
        new GenericArrayData(Array[Any](null, null))),
      dt))
  }

  test("MapType(LongType, BinaryType) - nullable values") {
    val dt = MapType(LongType, BinaryType, valueContainsNull = true)
    checkBoth(mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](0L, Long.MaxValue, -1L)),
        new GenericArrayData(Array[Any](Array[Byte](1, 2, 3), null, Array.empty[Byte]))),
      dt))
  }

  test("MapType(IntegerType, IntegerType) - non-nullable values") {
    val dt = MapType(IntegerType, IntegerType, valueContainsNull = false)
    checkBoth(mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](1, 2)),
        new GenericArrayData(Array[Any](10, 20))),
      dt))
  }

  // ---------------------------------------------------------------------------
  // StructType
  // ---------------------------------------------------------------------------

  test("StructType - flat: Int + String + Long") {
    val dt = new StructType()
      .add("a", IntegerType)
      .add("b", StringType)
      .add("c", LongType)

    // all non-null
    checkBoth(mkLit(
      new GenericInternalRow(Array[Any](42, UTF8String.fromString("hello"), 99L)),
      dt))
    // all null fields
    checkBoth(mkLit(
      new GenericInternalRow(Array[Any](null, null, null)),
      dt))
    // mixed nulls
    checkBoth(mkLit(
      new GenericInternalRow(Array[Any](1, null, Long.MaxValue)),
      dt))
    // null struct itself
    checkBoth(nullLit(dt))
  }

  test("StructType - nested struct") {
    val innerDt = new StructType()
      .add("x", IntegerType)
      .add("y", DoubleType)
    val outerDt = new StructType()
      .add("inner", innerDt)
      .add("label", StringType)

    val inner = new GenericInternalRow(Array[Any](1, 2.718))
    checkBoth(mkLit(
      new GenericInternalRow(Array[Any](inner, UTF8String.fromString("abc"))),
      outerDt))
    // null inner struct
    checkBoth(mkLit(
      new GenericInternalRow(Array[Any](null, UTF8String.fromString("xyz"))),
      outerDt))
  }

  test("StructType - struct containing array and map") {
    val arrDt = ArrayType(IntegerType, containsNull = true)
    val mapDt = MapType(StringType, LongType, valueContainsNull = true)
    val dt = new StructType()
      .add("arr", arrDt)
      .add("m", mapDt)
      .add("n", IntegerType)

    val arr = new GenericArrayData(Array[Any](1, null, 3))
    val map = new ArrayBasedMapData(
      new GenericArrayData(Array[Any](UTF8String.fromString("k"))),
      new GenericArrayData(Array[Any](42L)))

    checkBoth(mkLit(new GenericInternalRow(Array[Any](arr, map, 7)), dt))
    checkBoth(mkLit(new GenericInternalRow(Array[Any](null, null, null)), dt))
  }

  test("StructType - all scalar field types") {
    val date1 = DateTimeUtils.stringToDate(UTF8String.fromString("2024-06-01")).get
    val ts1 = DateTimeUtils.stringToTimestamp(
      UTF8String.fromString("2024-06-01 00:00:00"), ZoneOffset.UTC).get
    val tsNtz1 = DateTimeUtils.stringToTimestampWithoutTimeZone(
      UTF8String.fromString("2024-06-01 00:00:00")).get

    val dt = new StructType()
      .add("null_f",       NullType)
      .add("bool_f",       BooleanType)
      .add("byte_f",       ByteType)
      .add("short_f",      ShortType)
      .add("int_f",        IntegerType)
      .add("long_f",       LongType)
      .add("float_f",      FloatType)
      .add("double_f",     DoubleType)
      .add("decimal_f",    DecimalType.SYSTEM_DEFAULT)
      .add("string_f",     StringType)
      .add("binary_f",     BinaryType)
      .add("date_f",       DateType)
      .add("timestamp_f",  TimestampType)
      .add("timestampntz", TimestampNTZType)
      .add("daytime_f",    DayTimeIntervalType())
      .add("yearmonth_f",  YearMonthIntervalType())

    val row = new GenericInternalRow(Array[Any](
      null,
      true,
      42.toByte,
      1000.toShort,
      Int.MaxValue,
      Long.MinValue,
      3.14f,
      2.718,
      Decimal("123456.789012345678"),
      UTF8String.fromString("apache spark"),
      Array[Byte](0xde.toByte, 0xad.toByte, 0xbe.toByte, 0xef.toByte),
      date1,
      ts1,
      tsNtz1,
      Duration.ofDays(1).toNanos / 1000L,
      12
    ))

    checkBoth(mkLit(row, dt))

    // All-null row
    checkBoth(mkLit(
      new GenericInternalRow(Array.fill[Any](dt.length)(null)),
      dt))
  }

  // ---------------------------------------------------------------------------
  // VariantType - logical-type dispatch
  // ---------------------------------------------------------------------------

  test("VariantType") {
    def parseVariant(json: String): VariantVal =
      VariantExpressionEvalUtils.parseJson(UTF8String.fromString(json))
    Seq(
      parseVariant("null"),
      parseVariant("true"),
      parseVariant("42"),
      parseVariant("3.14"),
      parseVariant("\"hello\""),
      parseVariant("{\"a\":1,\"b\":2}"),
      parseVariant("[1,2,3]")
    ).foreach { v => checkBoth(mkLit(v, VariantType)) }
    checkBoth(nullLit(VariantType))
  }

  // ---------------------------------------------------------------------------
  // Order-invariance: Map and Variant
  // ---------------------------------------------------------------------------

  test("MapType - insertion-order invariance") {
    val dt = MapType(StringType, LongType, valueContainsNull = false)
    def mapLit(pairs: (String, Long)*): Expression = {
      val keys = new GenericArrayData(pairs.map(p => UTF8String.fromString(p._1): Any).toArray)
      val vals = new GenericArrayData(pairs.map(p => p._2: Any).toArray)
      mkLit(new ArrayBasedMapData(keys, vals), dt)
    }
    val h1 = XxHash3(Seq(mapLit("a" -> 1L, "b" -> 2L, "c" -> 3L)), 0L).eval(null)
    val h2 = XxHash3(Seq(mapLit("c" -> 3L, "a" -> 1L, "b" -> 2L)), 0L).eval(null)
    val h3 = XxHash3(Seq(mapLit("b" -> 2L, "c" -> 3L, "a" -> 1L)), 0L).eval(null)
    assert(h1 == h2 && h1 == h3, "Map hash must be insertion-order independent")
    val hAlt = XxHash3(Seq(mapLit("a" -> 1L, "b" -> 99L, "c" -> 3L)), 0L).eval(null)
    assert(h1 != hAlt, "Maps with different values must hash differently")
  }

  test("VariantType - object field-order invariance") {
    def parseVariant(json: String): VariantVal =
      VariantExpressionEvalUtils.parseJson(UTF8String.fromString(json))
    val h1 = XxHash3(Seq(mkLit(parseVariant("""{"a":1,"b":2}"""), VariantType)), 0L).eval(null)
    val h2 = XxHash3(Seq(mkLit(parseVariant("""{"b":2,"a":1}"""), VariantType)), 0L).eval(null)
    assert(h1 == h2, "Variant object hash must be field-order independent")
    val hAlt = XxHash3(
      Seq(mkLit(parseVariant("""{"a":1,"b":99}"""), VariantType)), 0L).eval(null)
    assert(h1 != hAlt, "Variant objects with different values must hash differently")
  }

  // ---------------------------------------------------------------------------
  // Multi-column hashing
  // ---------------------------------------------------------------------------

  test("XxHash3 - multiple columns, mixed types and nulls") {
    val exprs = Seq(
      Literal.create(42, IntegerType),
      Literal.create(UTF8String.fromString("hello"), StringType),
      Literal.create(null, LongType),
      Literal.create(3.14, DoubleType),
      Literal.create(Array[Byte](1, 2, 3), BinaryType))

    val expr3 = XxHash3(exprs, 0L)
    checkEvaluation(expr3, expr3.eval(null))

    val expr3s = XxHash3(exprs, 42L)
    checkEvaluation(expr3s, expr3s.eval(null))

    val expr128 = new XxHash128(exprs)
    val h1 = expr128.eval(null)
    val h2 = expr128.eval(null)
    assert(h1 != null)
    assert(java.util.Arrays.equals(h1.asInstanceOf[Array[Byte]], h2.asInstanceOf[Array[Byte]]))
  }

  // ---------------------------------------------------------------------------
  // Seed sensitivity
  // ---------------------------------------------------------------------------

  test("XxHash3 - seed sensitivity: distinct seeds produce distinct hashes") {
    val lit = Literal.create(UTF8String.fromString("spark"), StringType)
    val seeds = Seq(0L, 1L, 42L, Long.MaxValue, Long.MinValue)
    val hashes = seeds.map(s => XxHash3(Seq(lit), s).eval(null).asInstanceOf[Long])
    assert(hashes.distinct.size == seeds.size,
      s"Expected all seeds to produce distinct hashes but got: $hashes")
  }

  test("XxHash3 - seed 0 is deterministic across re-evaluations") {
    val lit = Literal.create(new GenericArrayData(Array[Any](1, 2, 3)), ArrayType(IntegerType))
    val expr = XxHash3(Seq(lit), 0L)
    val h1 = expr.eval(null).asInstanceOf[Long]
    val h2 = expr.eval(null).asInstanceOf[Long]
    assert(h1 == h2)
  }

  // ---------------------------------------------------------------------------
  // Boundary / regression cases
  // ---------------------------------------------------------------------------

  test("XxHash3 - -0.0 and 0.0 produce the same hash (Spark normalises -0.0)") {
    val pos = XxHash3(Seq(Literal.create(0.0, DoubleType)), 0L)
    val neg = XxHash3(Seq(Literal.create(-0.0, DoubleType)), 0L)
    checkEvaluation(pos, pos.eval(null))
    checkEvaluation(neg, neg.eval(null))
    assert(pos.eval(null) == neg.eval(null),
      "-0.0 and 0.0 must hash identically (SPARK-35207 regression)")
  }

  test("XxHash3 - -0.0f and 0.0f produce the same hash") {
    val pos = XxHash3(Seq(Literal.create(0.0f, FloatType)), 0L)
    val neg = XxHash3(Seq(Literal.create(-0.0f, FloatType)), 0L)
    assert(pos.eval(null) == neg.eval(null),
      "-0.0f and 0.0f must hash identically (SPARK-35207 regression)")
  }

  test("XxHash3 - empty binary and empty string are handled") {
    check3(Literal.create(Array.empty[Byte], BinaryType))
    check3(Literal.create(UTF8String.fromString(""), StringType))
  }

  // ---------------------------------------------------------------------------
  // Pinned golden values (algorithm-stability regression)
  // ---------------------------------------------------------------------------
  // These assert that specific inputs produce specific 64-bit outputs.
  // If they fail after an algorithm change, run XXH3TypeCoverageGoldenPrinter.main
  // and paste the new map into goldenXxHash3 above, but note that stored hashes
  // will no longer be compatible with previously computed values.

  private def checkGolden(key: String, lit: Expression): Unit = {
    val expected = XXH3TypeCoverageGoldenPrinter.goldenXxHash3(key)
    checkEvaluation(XxHash3(Seq(lit), 0L), expected)
  }

  test("pinned golden values - xxhash3 output is stable across Spark versions") {
    val date1 = DateTimeUtils.stringToDate(UTF8String.fromString("2024-01-15")).get
    val dateNeg = DateTimeUtils.stringToDate(UTF8String.fromString("1800-06-01")).get
    val ts1 = DateTimeUtils.stringToTimestamp(
      UTF8String.fromString("2024-01-15 12:34:56.789012"), ZoneOffset.UTC).get
    val tsNtz1 = DateTimeUtils.stringToTimestampWithoutTimeZone(
      UTF8String.fromString("2024-01-15 12:34:56.789012")).get
    val oneDayMicros = Duration.ofDays(1).toNanos / 1000L
    val iv1 = IntervalUtils.stringToInterval(
      UTF8String.fromString("interval 1 year 2 months 3 days 4 hours"))

    checkGolden("null/null",    nullLit(NullType))
    checkGolden("bool/false",   mkLit(false, BooleanType))
    checkGolden("bool/true",    mkLit(true, BooleanType))
    checkGolden("bool/null",    nullLit(BooleanType))
    checkGolden("byte/0",       mkLit(0.toByte, ByteType))
    checkGolden("byte/1",       mkLit(1.toByte, ByteType))
    checkGolden("byte/-1",      mkLit((-1).toByte, ByteType))
    checkGolden("byte/max",     mkLit(Byte.MaxValue, ByteType))
    checkGolden("byte/min",     mkLit(Byte.MinValue, ByteType))
    checkGolden("byte/null",    nullLit(ByteType))
    checkGolden("short/0",      mkLit(0.toShort, ShortType))
    checkGolden("short/1",      mkLit(1.toShort, ShortType))
    checkGolden("short/-1",     mkLit((-1).toShort, ShortType))
    checkGolden("short/max",    mkLit(Short.MaxValue, ShortType))
    checkGolden("short/min",    mkLit(Short.MinValue, ShortType))
    checkGolden("short/null",   nullLit(ShortType))
    checkGolden("int/0",        mkLit(0, IntegerType))
    checkGolden("int/1",        mkLit(1, IntegerType))
    checkGolden("int/-1",       mkLit(-1, IntegerType))
    checkGolden("int/max",      mkLit(Int.MaxValue, IntegerType))
    checkGolden("int/min",      mkLit(Int.MinValue, IntegerType))
    checkGolden("int/null",     nullLit(IntegerType))
    checkGolden("long/0",       mkLit(0L, LongType))
    checkGolden("long/1",       mkLit(1L, LongType))
    checkGolden("long/-1",      mkLit(-1L, LongType))
    checkGolden("long/max",     mkLit(Long.MaxValue, LongType))
    checkGolden("long/min",     mkLit(Long.MinValue, LongType))
    checkGolden("long/null",    nullLit(LongType))
    checkGolden("float/0",      mkLit(0.0f, FloatType))
    checkGolden("float/-0",     mkLit(-0.0f, FloatType))
    checkGolden("float/1.5",    mkLit(1.5f, FloatType))
    checkGolden("float/NaN",    mkLit(Float.NaN, FloatType))
    checkGolden("float/+Inf",   mkLit(Float.PositiveInfinity, FloatType))
    checkGolden("float/-Inf",   mkLit(Float.NegativeInfinity, FloatType))
    checkGolden("float/null",   nullLit(FloatType))
    checkGolden("double/0",     mkLit(0.0, DoubleType))
    checkGolden("double/-0",    mkLit(-0.0, DoubleType))
    checkGolden("double/1.5",   mkLit(1.5, DoubleType))
    checkGolden("double/NaN",   mkLit(Double.NaN, DoubleType))
    checkGolden("double/+Inf",  mkLit(Double.PositiveInfinity, DoubleType))
    checkGolden("double/-Inf",  mkLit(Double.NegativeInfinity, DoubleType))
    checkGolden("double/null",  nullLit(DoubleType))
    checkGolden("dec10/0",      mkLit(Decimal(0), DecimalType.USER_DEFAULT))
    checkGolden("dec10/1",      mkLit(Decimal(1), DecimalType.USER_DEFAULT))
    checkGolden("dec10/-1",     mkLit(Decimal(-1), DecimalType.USER_DEFAULT))
    checkGolden("dec10/null",   nullLit(DecimalType.USER_DEFAULT))
    checkGolden("dec38/0",      mkLit(Decimal(0), DecimalType.SYSTEM_DEFAULT))
    checkGolden("dec38/big",    mkLit(Decimal("123456.789012345678"), DecimalType.SYSTEM_DEFAULT))
    checkGolden("dec38/null",   nullLit(DecimalType.SYSTEM_DEFAULT))
    checkGolden("str/empty",    mkLit(UTF8String.fromString(""), StringType))
    checkGolden("str/hello",    mkLit(UTF8String.fromString("hello world"), StringType))
    checkGolden("str/17",       mkLit(UTF8String.fromString("x" * 17), StringType))
    checkGolden("str/129",      mkLit(UTF8String.fromString("y" * 129), StringType))
    checkGolden("str/300",      mkLit(UTF8String.fromString("z" * 300), StringType))
    checkGolden("str/null",     nullLit(StringType))
    checkGolden("bin/empty",    mkLit(Array.empty[Byte], BinaryType))
    checkGolden("bin/1byte",    mkLit(Array[Byte](0), BinaryType))
    checkGolden("bin/8bytes",   mkLit(Array[Byte](1, 2, 3, 4, 5, 6, 7, 8), BinaryType))
    checkGolden("bin/300",      mkLit(Array.fill[Byte](300)(42.toByte), BinaryType))
    checkGolden("bin/null",     nullLit(BinaryType))
    checkGolden("date/epoch",   mkLit(0, DateType))
    checkGolden("date/2024",    mkLit(date1, DateType))
    checkGolden("date/1800",    mkLit(dateNeg, DateType))
    checkGolden("date/null",    nullLit(DateType))
    checkGolden("ts/epoch",     mkLit(0L, TimestampType))
    checkGolden("ts/2024",      mkLit(ts1, TimestampType))
    checkGolden("ts/null",      nullLit(TimestampType))
    checkGolden("tsntz/epoch",  mkLit(0L, TimestampNTZType))
    checkGolden("tsntz/2024",   mkLit(tsNtz1, TimestampNTZType))
    checkGolden("tsntz/null",   nullLit(TimestampNTZType))
    checkGolden("dt/0",         mkLit(0L, DayTimeIntervalType()))
    checkGolden("dt/1day",      mkLit(oneDayMicros, DayTimeIntervalType()))
    checkGolden("dt/-1day",     mkLit(-oneDayMicros, DayTimeIntervalType()))
    checkGolden("dt/null",      nullLit(DayTimeIntervalType()))
    checkGolden("ym/0",         mkLit(0, YearMonthIntervalType()))
    checkGolden("ym/12",        mkLit(12, YearMonthIntervalType()))
    checkGolden("ym/-6",        mkLit(-6, YearMonthIntervalType()))
    checkGolden("ym/null",      nullLit(YearMonthIntervalType()))
    checkGolden("cal/zero",     mkLit(new CalendarInterval(0, 0, 0L), CalendarIntervalType))
    checkGolden("cal/mixed",    mkLit(iv1, CalendarIntervalType))
    checkGolden("cal/null",     nullLit(CalendarIntervalType))
    val tsNanosEpoch = TimestampNanosVal.fromParts(0L, 0.toShort)
    val tsNanosMixed = TimestampNanosVal.fromParts(1705318496789012L, 500.toShort)
    val tsNtz9 = TimestampNTZNanosType(9)
    val tsLtz9 = TimestampLTZNanosType(9)
    checkGolden("tsntz9/epoch", mkLit(tsNanosEpoch, tsNtz9))
    checkGolden("tsntz9/mixed", mkLit(tsNanosMixed, tsNtz9))
    checkGolden("tsntz9/null",  nullLit(tsNtz9))
    checkGolden("tsltz9/epoch", mkLit(tsNanosEpoch, tsLtz9))
    checkGolden("tsltz9/mixed", mkLit(tsNanosMixed, tsLtz9))
    checkGolden("tsltz9/null",  nullLit(tsLtz9))
    val aintDt = ArrayType(IntegerType, containsNull = false)
    checkGolden("aint/empty",   mkLit(new GenericArrayData(Array[Any]()), aintDt))
    checkGolden("aint/123",     mkLit(new GenericArrayData(Array[Any](1, 2, 3)), aintDt))
    checkGolden("aint/bounds",  mkLit(
      new GenericArrayData(Array[Any](Int.MinValue, 0, Int.MaxValue)), aintDt))
    checkGolden("aint/null",    nullLit(aintDt))
    val aintNDt = ArrayType(IntegerType, containsNull = true)
    checkGolden("aintn/nn",     mkLit(new GenericArrayData(Array[Any](null, null)), aintNDt))
    checkGolden("aintn/1n3",    mkLit(new GenericArrayData(Array[Any](1, null, 3)), aintNDt))
    val astrDt = ArrayType(StringType, containsNull = true)
    checkGolden("astr/mix",     mkLit(
      new GenericArrayData(Array[Any](
        UTF8String.fromString("hello"), null, UTF8String.fromString("world"))),
      astrDt))
    val mapDt = MapType(IntegerType, StringType, valueContainsNull = true)
    checkGolden("map/empty",    mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any]()), new GenericArrayData(Array[Any]())), mapDt))
    checkGolden("map/mix",      mkLit(
      new ArrayBasedMapData(
        new GenericArrayData(Array[Any](1, 2, 3)),
        new GenericArrayData(Array[Any](
          UTF8String.fromString("a"), null, UTF8String.fromString("c")))),
      mapDt))
    checkGolden("map/null",     nullLit(mapDt))
    val stDt = new StructType().add("a", IntegerType).add("b", StringType).add("c", LongType)
    checkGolden("st/vals",      mkLit(
      new GenericInternalRow(Array[Any](42, UTF8String.fromString("hello"), 99L)), stDt))
    checkGolden("st/nulls",     mkLit(
      new GenericInternalRow(Array[Any](null, null, null)), stDt))
    checkGolden("st/null",      nullLit(stDt))
    def parseVariant(json: String): VariantVal =
      VariantExpressionEvalUtils.parseJson(UTF8String.fromString(json))
    checkGolden("var/null_v",   mkLit(parseVariant("null"), VariantType))
    checkGolden("var/bool",     mkLit(parseVariant("true"), VariantType))
    checkGolden("var/long",     mkLit(parseVariant("42"), VariantType))
    checkGolden("var/double",   mkLit(parseVariant("3.14"), VariantType))
    checkGolden("var/string",   mkLit(parseVariant("\"hello\""), VariantType))
    checkGolden("var/object",   mkLit(parseVariant("{\"a\":1,\"b\":2}"), VariantType))
    checkGolden("var/array",    mkLit(parseVariant("[1,2,3]"), VariantType))
    checkGolden("var/sql_null", nullLit(VariantType))
  }
}
